### ISSUE TITLE
Add ome-zarr support

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-viewer#315]
Current state of the spec is here, @joshmoore?:

https://github.com/ome/omero-ms-zarr/blob/master/spec.md

**Comment by joshmoore** [comment]
Currently, yes. I'll post something when it moves.

**Comment by thewtex** [comment]
@joshmoore thanks!

**Comment by oeway** [comment]
Supporting ome-zarr or have a general way to interact with remote multi-resolution data would be awesome.

I had some discussion with others about potential way to display huge volume with itk-vtk-viewer from Python with imjoy-rpc, one potential solution is to support precomputed pyramid with zarr (as implemented in [vizarr](https://github.com/hms-dbmi/vizarr), but also for 3D).

Looking forward to this feature.

**Comment by joshmoore** [comment]
The spec has now moved to https://github.com/ome/ngff (rendered at: https://ngff.openmicroscopy.org/latest/)

**Comment by joshmoore** [comment]
Hi @thewtex. We were looking to start exploring the viewer for opening lightsheet data in OME-Zarr and ran across https://github.com/Kitware/itk-vtk-viewer/pull/343 & https://github.com/Kitware/itk-vtk-viewer/issues/176. A few questions:

 * which ticket/PR should we use for discussion? ;)
 * can you give us a status update?
 * is there anything you could use help with?
 * if yes, can you provide some pointers for getting started with the code base?

Hope all is well.
~Josh

**Comment by thewtex** [comment]
Hi @joshmoore !

Thanks for the questions, and comments! Yes #343 comprises a major refactoring that relates to multi-scale supported; it will be merged at the end of this week. This will initially support multi-scale support for large in-browser-memory images. However, I will immediately begin work to address #176, zarr, client-side backend support. I will provide an initial example link, but your feedback on both the zarr support and the viewer features will be *highly* appreciated! The refactoring is aiming for compatibility with OME-Zarr and the ome-zarr label features. But, I am sure that your participation would improve both the standard compatibility and viewer features. Looking forward to working with you! Stay safe and well.

**Comment by oeway** [comment]
@thewtex Wondering what left to support ome-zarr format?

**Comment by thewtex** [comment]
We have to support the different dimension order / memory layout of ome-zarr (contiguous channels) in addition to the current support, (interleaved channels).

I will implement this after adding support for selection of a region of interest.

**Comment by thewtex** [comment]
Test suite data sets:

- https://github.com/ome/ome_zarr_test_suite/tree/main/data

**Comment by joshmoore** [comment]
@sbesson has also been working on the next batch of v0.4 data that will get pushed to EBI's S3. (As so often, largely blocked by naming discussions. :wink:) It is likely to contain at least some of @constantinpape's samples from https://github.com/ome/ome-ngff-prototypes

**Comment by PaulHax** [comment]
#465 Starts support of 0.4
TODO: 
Add translate transform.
Add multi channel support.
Add test for datasets here: https://github.com/ome/ome-ngff-prototypes and https://github.com/ome/ome_zarr_test_suite/tree/main/data

**Comment by oeway** [comment]
Great work @PaulHax ! I am wondering whether I can use it already through the ImJoy API (i.e. the [setImage](https://github.com/Kitware/itk-vtk-viewer/blob/21d44e447205c18b5708ad0ffeb918ed4e5e3c65/src/imJoyPluginAPI.js#L66) function)? What's the format? Can I pass a zarr store? I would like to test it in [jupyter lite](https://jupyter.imjoy.io/lab/index.html) so we can view large zarr files in the browser.

**Comment by PaulHax** [comment]
Thank you @oeway .  `setImage` can take a URL object pointing to the store:

`new URL(https://minio-dev.openmicroscopy.org/idr/v0.4/2022-02-03/idr0062/6001240.zarr)`

The viewer then loads the entire least detailed image.  If the frame rate is high enough, the viewer may continue fetching more detailed images.

**Comment by oeway** [comment]
@PaulHax Can we allow passing a store object (with `getItem(key)` and `containsItem(key)` functions) to `setImage`? The idea is that we will use the imjoy-rpc layer to proxy a store implemented in Python and pass it to `setImage` in itk-vtk-viewer.

**Comment by PaulHax** [comment]
Ah, yes.  Passing a "Store" object with with a `getItem(key)` function to `setImage` also works.

**Comment by oeway** [comment]
Great! Looks like the store object is detected, however, the viewer detects the image, but it give me `KeyError: '3/0undefined0undefined0undefined1undefined0undefine'`. 

Full browser log:
[jupyter.imjoy.io-1650558105187.log](https://github.com/Kitware/itk-vtk-viewer/files/8532731/jupyter.imjoy.io-1650558105187.log)


Here is how to reproduce:
1. download [itk-vtk-viewer-demo-ome-zarr.ipynb.zip](https://github.com/Kitware/itk-vtk-viewer/files/8532760/itk-vtk-viewer-demo-ome-zarr.ipynb.zip) and unzip the notebook
2. open https://jupyter.imjoy.io/lab/index.html drag and drop the notebook to the file tree located on the left side, then double click to open it.
3. Wait until you see an ImJoy icon in the toolbar, then execute line by line.
4. In the notebook, I created a small ome-zarr file, which has already been tested with [vizarr](https://github.com/hms-dbmi/vizarr), you can also run the last cell to see how it looks like in vizarr.
5. If you want to debug with your local instance of itk-vtk-viewer, replace `"https://kitware.github.io/itk-vtk-viewer/app"` into your local url.

**Comment by PaulHax** [comment]
@oeway Thank for the step by step and the new test case.  Threw in a default "dimension_separator" in #472 to keep the errors at bay.  Still need to do multi-channel though.

**Comment by oeway** [comment]
@PaulHax Great, thanks for the quick fix!


It works now!
![Screenshot 2022-04-22 at 08 13 55](https://user-images.githubusercontent.com/478667/164614504-122764c5-138c-422d-9377-a2857d563879.png)

Looking forward to the multi-channel support too.

**Comment by oeway** [comment]
@thewtex BTW, any timeline for the multi-channel support? Really excited about the progress here!

**Comment by thewtex** [comment]
@oeway love to see the imjoy/jupyterlite demo!

multi-channel support is expected within the next two weeks.

**Comment by oeway** [comment]
> @oeway love to see the imjoy/jupyterlite demo!
> 
> multi-channel support is expected within the next two weeks.

Sounds great! Looking forward.


BTW, I just tried the jupyterlite demo again, and it seems the latest itk-vtk-viewer doesn't show the zarr image anymore.

To reproduce, the ImJoy flavor of jupyterlite now support loading notebooks from URL, so one can click a like like this to see the itk-vtk-viewer NGFF demo: https://jupyter.imjoy.io/lab/index.html?load=https://gist.github.com/oeway/4a3ec3866eae199f982b8b81bf72a3a8&open=1

@PaulHax @thewtex

**Comment by oeway** [comment]
Hi @thewtex Thanks for testing it. I did run individually, however, I still don't see the image:
<img width="1532" alt="Screen Shot 2022-04-29 at 11 42 21 PM" src="https://user-images.githubusercontent.com/478667/166072971-4c5062f8-dc6c-4811-b1d6-bc6d1deeb7eb.png">
I am using Chrome Version 100.0.4896.127 (Official Build) (x86_64)

**Comment by thewtex** [comment]
@oeway v12.3.0 incorporates #480 , interested to know if you still have this issue?

**Comment by oeway** [comment]
> @oeway v12.3.0 incorporates #480 , interested to know if you still have this issue?

Thank you, after reloading, I get the latest version! However, there seems to be an issue with the display:
<img width="1054" alt="Screen Shot 2022-05-18 at 9 51 27 PM" src="https://user-images.githubusercontent.com/478667/169144420-cdb99c4e-0703-4cc4-b051-d0b7ebdb660d.png">

Try it here with Chrome: https://jupyter.imjoy.io/lab/index.html?load=https://gist.github.com/oeway/4a3ec3866eae199f982b8b81bf72a3a8&open=1

**Comment by oeway** [comment]
Hey, @thewtex It's working! Now it's actually comes nicely together! (It seems still dim though, is the fix deployed?)

I am now using zarr+ZipStore to access a remote zipped NGFF file served from an S3 server (with the possibility to add authentication using presigned URL), completely in Pyodide/JupyterLite.

Try it here: https://jupyter.imjoy.io/lab/index.html?load=https://gist.github.com/oeway/391b4352ea57b5682366ce3dc2fa9174&open=1

![Screenshot 2022-05-19 at 10 21 24](https://user-images.githubusercontent.com/478667/169247541-bda320d6-bc58-4d57-af8d-44926cf8e788.png)

**Comment by thewtex** [comment]
@oeway yes, that is quite annoying. The #488 corrected the Window/Level locally (same behavior was observer), but I also still see the issue with the 2D Zarr. Passing the issue to @PaulHax :gift:

**Comment by thewtex** [comment]
With #499 , released in 13.0.0, the 2D multi-component rendering is now addressed! :tada: :taco: h/t @PaulHax 

Verified by clearing the cache with your example @oeway :+1: 

![image](https://user-images.githubusercontent.com/25432/174189118-6c5916e5-fdf1-4a8e-92af-ec4696ba7610.png)

We now have a good test suite demonstrating support for a number of OME-NGFF-Zarr images, so closing. If new issues are discovered, let's create new issues to start fresh threads. Thanks!

**Comment by joshmoore** [comment]
:tada: Looking forward to passing out the likes of https://kitware.github.io/itk-vtk-viewer/app/?image=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001241.zarr&rotate=false to people :smile:

**Comment by oeway** [comment]
FYI: @thewtex the following link does not give me the but only 2 channels in the UI:

> https://kitware.github.io/itk-vtk-viewer/app/?image=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001241.zarr&rotate=false
